services:
  - type: web
    name: water-quality-prediction
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.16
    autoDeploy: true
